name: Build Flet APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Cache Flutter SDK
        uses: actions/cache@v4
        with:
          path: ~/.flet/flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('requirements.txt') }}

      - name: Build APK
        run: flet build apk . --verbose

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: flet-apk
          path: build/apk/**/*.apk
